### ISSUE TITLE
Integration Problem

### ISSUE THREAD

**Issue by medziedcherif-tn** [AlanAcDz/angular-zoom-iframe#1]
```
core.js:5980 ERROR TypeError: Cannot read properties of null (reading '0')
    at M (zoomus-websdk.umd.min.js:2:1380706)
    at combination (combineReducers.js:120:1)
    at dispatch (createStore.js:165:1)
    at index.js:14:1
    at Object.zmg_initMeetingConfig (bindActionCreators.js:3:1)
    at a.value (zoomus-websdk.umd.min.js:2:3946794)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:28289:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
```

Could you help me please this is urgent !

**Comment by AlanAcDz** [comment]
It seems like an issue with the zoom sdk itself, I cannot tell without more context though
